name: terraform plan

on:
  pull_request:
    branches:
      - main

jobs:
  terraformplan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Set up AWS CLI on the runner
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: "us-east-1"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID}}

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan
        env:
           AWS_ACCESS_KEY_ID: ${{ secrets.MY_AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.MY_AWS_SECRET_KEY_ID }}
           AWS_DEFAULT_REGION: us-east-1

